[package]
name = "switcheroo"
version = "2.6.0"
edition = "2024"
rust-version = "1.92"

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
unwrap_used = "allow"
wildcard_imports = "allow"
future_not_send = "allow"
cast_possible_truncation = "allow"
cast_sign_loss = "allow"
cast_possible_wrap = "allow"
cast_precision_loss = "allow"

[dependencies]
gettext-rs = { version = "0.8", features = ["gettext-system"] }
glib = "0.22"
gtk = { version = "0.11", package = "gtk4", features = ["gnome_50"] }
gtk-macros = { version = "0.11", package = "gtk4-macros" }
adw = { version = "0.9", package = "libadwaita", features = ["v1_10"] }
log = "0.4"
pretty_env_logger = "0.5"
itertools = "0.15"
tokio = { version = "1.53", features = ["process", "rt", "rt-multi-thread"] }
futures = "0.3"
ashpd = { version = "0.13", features = ["open_uri"] }
tempfile = "3"
regex = "1.13"
rand = "0.10"
shared_child = "1.1"
fdlimit = "0.3"
derivative = "2.2"
async-channel = "2.5"
